modLoader = "javafml"
loaderVersion = "[45,)"
license = "All Rights Reserved"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"
[[mods]]
modId = "eternalmagic"
version = "${file.jarVersion}"
displayName = "Eternal Magic"
# A URL to query for updates for this mod. See the JSON update specification https://docs.minecraftforge.net/en/latest/misc/updatechecker/
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
#logoFile="EternalMagic.png"
credits="Minecraft Forge Community"
authors="Diamantino Op"
displayTest="MATCH_VERSION"
description = '''

'''

[[dependencies.eternalmagic]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.eternalmagic]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,1.20)"
ordering = "NONE"
side = "BOTH"
